// Bundles the headless Office engine into a self-contained CJS bundle plus a
// thin ESM wrapper, so a host can `import '@genoffice/office-ai'` without
// resolving any GenOffice monorepo path. The same technique as packages/cli:
// everything is inlined except the two things that cannot be (jsdom reads its
// own stylesheet from disk; mermaid is only reached by a lazy markdown diagram
// renderer that never runs headless). pdfium.wasm is copied beside the entry
// point so the bundle finds it without a repo checkout.
//
// Why CJS-primary rather than two real bundles: some transitively-inlined
// dependencies are CJS-only (word-extractor `require`s `buffer`), and esbuild
// cannot emulate `require` in an ESM output — it emits a "Dynamic require of
// X is not supported" throw. A real CJS build has no such problem, and an ESM
// consumer can load it through a generated wrapper, so we ship one real bundle
// and one generated façade.
import { build } from 'esbuild'
import { spawnSync } from 'node:child_process'
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const { version } = JSON.parse(await readFile(join(here, 'package.json'), 'utf8'))

// Vite's `?raw` text imports (the pptx op guides are markdown files)
const rawText = {
  name: 'raw-text',
  setup(b) {
    b.onResolve({ filter: /\?raw$/ }, (args) => ({
      path: resolve(args.resolveDir, args.path.replace(/\?raw$/, '')),
      namespace: 'raw-text',
    }))
    b.onLoad({ filter: /.*/, namespace: 'raw-text' }, async (args) => ({
      contents: await readFile(args.path, 'utf8'),
      loader: 'text',
    }))
  },
}

const outfile = join(here, 'dist/office-ai.cjs')

const result = await build({
  entryPoints: [join(here, 'src/index.ts')],
  outfile,
  bundle: true,
  platform: 'node',
  target: 'node22',
  logLevel: 'info',
  metafile: true,
  jsx: 'automatic',
  // jsdom reads its own stylesheet from disk and cannot be inlined; it ships
  // beside the bundle (declared as a dependency).
  // mermaid is only reached by the markdown editor's lazy diagram renderer,
  // which never runs headless.
  external: ['electron', 'jsdom', 'mermaid'],
  loader: {
    '.css': 'empty',
    '.ttf': 'empty',
    '.woff': 'empty',
    '.woff2': 'empty',
    '.svg': 'empty',
    '.png': 'empty',
  },
  plugins: [rawText],
  format: 'cjs',
  // esbuild leaves import.meta empty in cjs output; deps use import.meta.url
  // for asset lookups, so give them the bundle's own location.
  define: {
    'import.meta.url': '__officeAiImportMetaUrl',
    __GENOFFICE_VERSION__: JSON.stringify(version),
  },
  banner: {
    js: "const __officeAiImportMetaUrl = require('node:url').pathToFileURL(__filename).href;",
  },
})

// The ESM entry is a generated re-export façade over the CJS bundle, so the
// two entries never drift. esbuild does not report export names for CJS
// output, so enumerate them with a throwaway in-memory ESM pass over the same
// entry point (never written to disk).
const probe = await build({
  entryPoints: [join(here, 'src/index.ts')],
  bundle: true,
  write: false,
  metafile: true,
  platform: 'node',
  target: 'node22',
  logLevel: 'silent',
  format: 'esm',
  jsx: 'automatic',
  external: ['electron', 'jsdom', 'mermaid'],
  loader: { '.css': 'empty', '.ttf': 'empty', '.woff': 'empty', '.woff2': 'empty', '.svg': 'empty', '.png': 'empty' },
  plugins: [rawText],
  define: { __GENOFFICE_VERSION__: JSON.stringify(version) },
})
const probeOut = Object.keys(probe.metafile.outputs).find((k) => k.endsWith('.js'))
if (!probeOut) throw new Error('esbuild probe did not report an output')
const names = (probe.metafile.outputs[probeOut].exports ?? []).filter((name) => name !== 'default')
if (names.length === 0) throw new Error('esbuild probe reported no exports')
writeFileSync(
  join(here, 'dist/office-ai.mjs'),
  `// Generated by build.mjs — the ESM view of the CJS bundle. Do not edit.
import { createRequire } from 'node:module'
const require = createRequire(import.meta.url)
const mod = require('./office-ai.cjs')
export default mod
${names.map((name) => `export const ${name} = mod.${name}`).join('\n')}
`,
)

// The UI host tier (loopback HTTP face + renderer asset serving) ships as a
// second CJS bundle so the headless main bundle stays free of node:http and
// the handler modules. Consumed via `require('@genoffice/office-ai/host')`.
await build({
  entryPoints: [join(here, 'src/ui/index.ts')],
  outfile: join(here, 'dist/host.cjs'),
  bundle: true,
  platform: 'node',
  target: 'node22',
  logLevel: 'info',
  jsx: 'automatic',
  external: ['electron', 'jsdom', 'mermaid'],
  loader: {
    '.css': 'empty',
    '.ttf': 'empty',
    '.woff': 'empty',
    '.woff2': 'empty',
    '.svg': 'empty',
    '.png': 'empty',
  },
  plugins: [rawText],
  format: 'cjs',
  define: {
    'import.meta.url': '__officeAiImportMetaUrl',
    __GENOFFICE_VERSION__: JSON.stringify(version),
  },
  banner: {
    js: "const __officeAiImportMetaUrl = require('node:url').pathToFileURL(__filename).href;",
  },
})

// Same generated-ESM-façade treatment for the host tier.
const hostProbe = await build({
  entryPoints: [join(here, 'src/ui/index.ts')],
  bundle: true,
  write: false,
  metafile: true,
  platform: 'node',
  target: 'node22',
  logLevel: 'silent',
  format: 'esm',
  jsx: 'automatic',
  external: ['electron', 'jsdom', 'mermaid'],
  loader: { '.css': 'empty', '.ttf': 'empty', '.woff': 'empty', '.woff2': 'empty', '.svg': 'empty', '.png': 'empty' },
  plugins: [rawText],
  define: { __GENOFFICE_VERSION__: JSON.stringify(version) },
})
const hostProbeOut = Object.keys(hostProbe.metafile.outputs).find((k) => k.endsWith('.js'))
if (!hostProbeOut) throw new Error('esbuild host probe did not report an output')
const hostNames = (hostProbe.metafile.outputs[hostProbeOut].exports ?? []).filter(
  (name) => name !== 'default',
)
if (hostNames.length === 0) throw new Error('esbuild host probe reported no exports')
writeFileSync(
  join(here, 'dist/host.mjs'),
  `// Generated by build.mjs — the ESM view of the CJS host bundle. Do not edit.
import { createRequire } from 'node:module'
const require = createRequire(import.meta.url)
const mod = require('./host.cjs')
export default mod
${hostNames.map((name) => `export const ${name} = mod.${name}`).join('\n')}
`,
)

// pdfium.wasm powers the PDF reader, converter and rasterizer. Ship it beside
// the entry point (dist/wasm/) so src/resources.ts finds it without a checkout.
const wasm = resolveWasm()
if (wasm) {
  mkdirSync(join(here, 'dist/wasm'), { recursive: true })
  cpSync(wasm, join(here, 'dist/wasm/pdfium.wasm'))
  console.log(`office-ai: bundled pdfium.wasm from ${wasm}`)
} else {
  console.warn('office-ai: pdfium.wasm not found; PDF support will need GENOFFICE_PDFIUM_WASM')
}

function resolveWasm() {
  const env = process.env.GENOFFICE_PDFIUM_WASM
  for (const from of [join(here, 'package.json'), join(here, '..', '..', 'package.json')]) {
    try {
      return createRequire(from).resolve('@embedpdf/pdfium/pdfium.wasm')
    } catch {}
  }
  if (env && existsSync(env)) return env
  return null
}

// Declaration emit (see tsconfig.build.json): rootDir is the repo root, so the
// program's whole sibling-source closure lands under dist/types-all instead of
// being scattered next to sources. Keep only this package's subtree at
// dist/types — the emitted declarations reference nothing outside it.
const { status: tscStatus } = spawnSync(
  process.execPath,
  [
    join(
      dirname(createRequire(join(here, 'package.json')).resolve('typescript/package.json')),
      'bin',
      'tsc',
    ),
    '-p',
    join(here, 'tsconfig.build.json'),
  ],
  { stdio: 'inherit' },
)
if (tscStatus !== 0) throw new Error(`tsc declaration emit failed (${tscStatus})`)
const typesAll = join(here, 'dist/types-all')
const ownTypes = join(typesAll, 'packages/office-ai/src')
if (!existsSync(join(ownTypes, 'index.d.ts'))) {
  throw new Error('declaration emit produced no index.d.ts')
}
rmSync(join(here, 'dist/types'), { recursive: true, force: true })
cpSync(ownTypes, join(here, 'dist/types'), { recursive: true })
rmSync(typesAll, { recursive: true, force: true })
console.log('office-ai: declarations emitted to dist/types')
