/**
 * slides stubs (batch B): more placeholder handlers preserved verbatim.
 */

import { registerHandle } from '../common/registry.js'

export function registerSlidesStubsB(): void {
  registerHandle('slides:get-run-links', () => [])
  registerHandle('slides:group-elements', () => ({ ok: true, groupId: `group-${Date.now()}` }))
  registerHandle('slides:has-slide-clipboard', () => false)
  registerHandle('slides:history-batch-begin', () => ({ ok: true }))
  registerHandle('slides:history-batch-end', () => ({ ok: true }))
  registerHandle('slides:insert-image', () => ({ ok: true }))
  registerHandle('slides:is-dirty', () => false)
  registerHandle('slides:master-close', () => ({ ok: true }))
  registerHandle('slides:master-delete-element', () => ({ ok: true }))
  registerHandle('slides:master-edit-fill', () => ({ ok: true }))
  registerHandle('slides:master-edit-stroke', () => ({ ok: true }))
  registerHandle('slides:master-edit-text', () => ({ ok: true }))
  registerHandle('slides:master-edit-transform', () => ({ ok: true }))
  registerHandle('slides:master-enter', () => ({ ok: true }))
  registerHandle('slides:master-open', () => ({ ok: true }))
  registerHandle('slides:media-data', () => ({}))
  registerHandle('slides:move-section', () => ({ ok: true }))
  registerHandle('slides:move-slide', () => ({ ok: true }))
  registerHandle('slides:native-clipboard', () => ({}))
  registerHandle('slides:paste-elements', () => ({ ok: true }))
  registerHandle('slides:paste-slide', () => ({ ok: true }))
  registerHandle('slides:presenter-end', () => ({ ok: true }))
  registerHandle('slides:presenter-start', () => ({ ok: true }))
  registerHandle('slides:presenter-swap', () => ({ ok: true }))
  registerHandle('slides:remove-section', () => ({ ok: true }))
  registerHandle('slides:rename-section', () => ({ ok: true }))
  registerHandle('slides:reorder-element', () => ({ ok: true }))
  registerHandle('slides:replace-picture-bytes', () => ({ ok: true }))
  registerHandle('slides:set-advance-times', () => ({ ok: true }))
  registerHandle('slides:set-animations', () => ({ ok: true }))
  registerHandle('slides:set-element-font', () => ({ ok: true }))
  registerHandle('slides:set-element-paragraph-format', () => ({ ok: true }))
  registerHandle('slides:set-hidden', () => ({ ok: true }))
  registerHandle('slides:set-link', () => ({ ok: true }))
  registerHandle('slides:set-notes', () => ({ ok: true }))
  registerHandle('slides:set-sections', () => ({ ok: true }))
  registerHandle('slides:set-slide-layout', () => ({ ok: true }))
  registerHandle('slides:set-slide-size', () => ({ ok: true }))
  registerHandle('slides:set-table-cell-anchor', () => ({ ok: true }))
  registerHandle('slides:set-table-col-width', () => ({ ok: true }))
  registerHandle('slides:set-table-row-height', () => ({ ok: true }))
  registerHandle('slides:set-transition', () => ({ ok: true }))
  registerHandle('slides:show-fullscreen', () => ({ ok: true }))
  registerHandle('slides:table-merge', () => ({ ok: true }))
  registerHandle('slides:table-structure', () => ({}))
  registerHandle('slides:ungroup-element', () => ({ ok: true }))
  registerHandle('slides:add-comment', () => ({ ok: true, commentId: `comment-${Date.now()}` }))
  registerHandle('slides:add-ink', () => ({ ok: true }))
  registerHandle('slides:add-media-bytes', () => ({ ok: true }))
  registerHandle('slides:add-section', () => ({ ok: true, sectionId: `section-${Date.now()}` }))
  registerHandle('slides:add-slide-with-layout', () => ({ ok: true, slideId: `slide-${Date.now()}` }))
  registerHandle('slides:add-smartart', () => ({ ok: true }))
  registerHandle('slides:ai-snapshot-restore', () => ({ ok: true }))
  registerHandle('slides:audience-ready', () => ({ ok: true }))
  registerHandle('slides:cloud-gen-status', () => ({ status: 'idle' }))
}
