/**
 * slides stubs (batch A): placeholder handlers preserved verbatim from the
 * monolith. Per Phase 1.1 acceptance, the **internal logic** of these
 * handlers is left intact for Phase 1.2 / 1.3 follow-ups.
 */

import { registerHandle } from '../common/registry.js'

export function registerSlidesStubsA(): void {
  registerHandle('slides:export-pdf', () => ({ ok: true, message: '请使用浏览器的打印功能导出 PDF' }))
  registerHandle('slides:consume-pending-open', () => null)
  registerHandle('slides:add-blank-slide', () => ({ ok: true, slideId: `slide-${Date.now()}` }))
  registerHandle('slides:add-slide', () => ({ ok: true, slideId: `slide-${Date.now()}` }))
  registerHandle('slides:add-chart', () => ({ ok: true, chartId: `chart-${Date.now()}` }))
  registerHandle('slides:add-image-bytes', () => ({ ok: true, imageId: `image-${Date.now()}` }))
  registerHandle('slides:add-table', () => ({ ok: true, tableId: `table-${Date.now()}` }))
  registerHandle('slides:add-text', () => ({ ok: true, elementId: `text-${Date.now()}` }))
  registerHandle('slides:add-element', () => ({ ok: true, elementId: `element-${Date.now()}` }))
  registerHandle('slides:edit-text', () => ({ ok: true }))
  registerHandle('slides:delete-element', () => ({ ok: true }))
  registerHandle('slides:undo', () => ({ ok: true }))
  registerHandle('slides:redo', () => ({ ok: true }))
  registerHandle('slides:get-render-slides', () => [])
  registerHandle('slides:get-animations', () => [])
  registerHandle('slides:get-chart-data', () => ({}))
  registerHandle('slides:get-comments', () => [])
  registerHandle('slides:get-header-footer', () => ({ enabled: false }))
  registerHandle('slides:get-layouts', () => [])
  registerHandle('slides:get-link', () => null)
  registerHandle('slides:get-notes', () => '')
  registerHandle('slides:get-sections', () => [])
  registerHandle('slides:get-shape-keys', () => [])
  registerHandle('slides:get-slide-links', () => [])
  registerHandle('slides:get-slide-size', () => ({ width: 960, height: 540 }))
  registerHandle('slides:get-transition', () => ({ type: 'none', duration: 0 }))
  registerHandle('slides:apply-edit-script', () => ({ ok: true }))
  registerHandle('slides:apply-header-footer', () => ({ ok: true }))
  registerHandle('slides:apply-theme', () => ({ ok: true }))
  registerHandle('slides:apply-txn', () => ({ ok: true }))
  registerHandle('slides:batch-edit-transform', () => ({ ok: true }))
  registerHandle('slides:chart-color-schemes', () => [])
  registerHandle('slides:clipboard-external', () => ({}))
  registerHandle('slides:clipboard-probe', () => ({}))
  registerHandle('slides:copy-elements', () => ({ ok: true }))
  registerHandle('slides:copy-slide', () => ({ ok: true, slideId: `slide-${Date.now()}` }))
  registerHandle('slides:delete-comment', () => ({ ok: true }))
  registerHandle('slides:delete-slide', () => ({ ok: true }))
  registerHandle('slides:duplicate-elements', () => ({ ok: true }))
  registerHandle('slides:edit-background', () => ({ ok: true }))
  registerHandle('slides:edit-chart', () => ({ ok: true }))
  registerHandle('slides:edit-connector-endpoints', () => ({ ok: true }))
  registerHandle('slides:edit-fill', () => ({ ok: true }))
  registerHandle('slides:edit-image-fill', () => ({ ok: true }))
  registerHandle('slides:edit-picture-opacity', () => ({ ok: true }))
  registerHandle('slides:edit-picture-src-rect', () => ({ ok: true }))
  registerHandle('slides:edit-stroke', () => ({ ok: true }))
  registerHandle('slides:edit-table-cell', () => ({ ok: true }))
  registerHandle('slides:edit-table-style', () => ({ ok: true }))
  registerHandle('slides:edit-transform', () => ({ ok: true }))
  registerHandle('slides:find-replace', () => ({ ok: true, count: 0 }))
  registerHandle('slides:flip-elements', () => ({ ok: true }))
  registerHandle('slides:font-catalog', () => [])
  registerHandle('slides:font-missing', () => [])
  registerHandle('slides:font-download', () => ({ ok: true, message: 'Web 版本不支持字体下载' }))
  registerHandle('slides:font-install-local', () => ({ ok: true }))
  registerHandle('slides:insert-model3d', () => ({ ok: true }))
}
