/**
 * Embedded minimal-Office templates used to materialise a real, openable file
 * for a `*-new-blank` channel when the caller has no bytes to write yet.
 *
 * Without this fallback, `slides:new-blank` and `sheets:new-blank` would
 * create a recents row that points at a path that was never written to —
 * the renderer fires the channel as part of its "no file yet, give me a
 * blank deck" boot path, with `opts.pptx`/`opts.xlsx` undefined. The
 * recents grid then surfaces a "missing" tile that cannot be opened.
 *
 * `home:new-*` already calls this directly. Slides / sheets can reach the
 * same outcome by routing through {@link writeBlankOfficeFile} below.
 *
 * Templates are base64-encoded minimal OOXML zips; decoding them at
 * module-load time keeps the call sites allocation-free.
 */
import { writeFileSync } from 'node:fs'

const BLANK_TEMPLATES: Readonly<Record<'docx' | 'xlsx' | 'pptx', string>> = {
  docx: 'UEsDBBQAAAAIAJibNF3JTxqw6wAAAK4BAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbH1QvU7DMBDeeQrLK4odGBBCSTrwMwJDeYCTfUks7LPlc0v79jht6YAK4933q69b7YIXW8zsIvXyRrVSIJloHU29/Fi/NPdScAGy4CNhL/fIcjVcdet9QhZVTNzLuZT0oDWbGQOwigmpImPMAUo986QTmE+YUN+27Z02kQpSacriIYfuCUfY+CKed/V9LJLRsxSPR+KS1UtIyTsDpeJ6S/ZXSnNKUFV54PDsEl9XgtQXExbk74CT7q0uk51F8Q65vEKoLP0Vs9U2mk2oSvW/zYWecRydwbN+cUs5GmSukwevzkgARz/99WHu4RtQSwMEFAAAAAgAmJs0XbmBRHGwAAAAKgEAAAsAAABfcmVscy8ucmVsc43POw7CMAwG4J1TRN5pWgaEUJMuCKkrKgeIEjeNaB5KwqO3JwMDIAZG278/y233sDO5YUzGOwZNVQNBJ70yTjM4D8f1DkjKwikxe4cMFkzQ8VV7wlnkspMmExIpiEsMppzDntIkJ7QiVT6gK5PRRytyKaOmQciL0Eg3db2l8d0A/mGSXjGIvWqADEvAf2w/jkbiwcurRZd/nPhKFFlEjZnB3UdF1atdFRYob+nHi/wJUEsDBBQAAAAIAJibNF2BH5CQmAAAAMoAAAARAAAAd29yZC9kb2N1bWVudC54bWxFzsEOgjAMBuC7T7H0LkMPxhA2bj6BPsDcKpCwdtmmyNs7MMbL1zRt/rbt3n4SL4xpZFJwqGoQSJbdSL2C2/WyP4NI2ZAzExMqWDBBp3ft3Di2T4+URUmg1MwKhpxDI2WyA3qTKg5IZfbg6E0ubezlzNGFyBZTKgf8JI91fZLejAS6RN7ZLWsNK3El61b+jJth87sp/1/oD1BLAQIUAxQAAAAIAJibNF3JTxqw6wAAAK4BAAATAAAAAAAAAAAAAACAAQAAAABbQ29udGVudF9UeXBlc10ueG1sUEsBAhQDFAAAAAgAmJs0XbmBRHGwAAAAKgEAAAsAAAAAAAAAAAAAAIABHAEAAF9yZWxzLy5yZWxzUEsBAhQDFAAAAAgAmJs0XYEfkJCYAAAAygAAABEAAAAAAAAAAAAAAIAB9QEAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAADAAMAuQAAALwCAAAAAA==',
  xlsx: 'UEsDBBQAAAAIAJibNF3FLx19AAEAAC4CAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbK2RzU7DMBCE7zyF5WsVO+WAEErSQ4EjcCgPsDibxIr/5HVL+vY4aeGAClw4reyZ2W9kV5vJGnbASNq7mq9FyRk65Vvt+pq/7h6LW84ogWvBeIc1PyLxTXNV7Y4BieWwo5oPKYU7KUkNaIGED+iy0vloIeVj7GUANUKP8rosb6TyLqFLRZp38Ka6xw72JrGHKV+fikQ0xNn2ZJxZNYcQjFaQsi4Prv1GKc4EkZOLhwYdaJUNXF4kzMrPgHPuOb9M1C2yF4jpCWx2ycnIdx/HN+9H8fuSCy1912mFrVd7myOCQkRoaUBM1ohlCgvarf7mL2aSy1j/c5Gv/Z895PLdzQdQSwMEFAAAAAgAmJs0XQZZx4KxAAAAKAEAAAsAAABfcmVscy8ucmVsc43PsQ6CMBAG4N2naG6XgoMxhsJiTFgNPkBtj0KAXtNWhbe3oxoHx8v99/25sl7miT3Qh4GsgCLLgaFVpAdrBFzb8/YALERptZzIooAVA9TVprzgJGO6Cf3gAkuIDQL6GN2R86B6nGXIyKFNm478LGMaveFOqlEa5Ls833P/bkD1YbJGC/CNLoC1q8N/bOq6QeGJ1H1GG39UfCWSLL3BKGCZ+JP8eCMas4QCr0r+8WD1AlBLAwQUAAAACACYmzRdd0D+xLwAAAAcAQAADwAAAHhsL3dvcmtib29rLnhtbI1Py47CMAy88xWR70vaPSBUteWCkDgvfEBoXBrR2JWd5fH3hNed04w1mvFMvbrG0ZxRNDA1UM4LMEgd+0DHBva7zc8SjCZH3o1M2MANFVbtrL6wnA7MJ5P9pA0MKU2VtdoNGJ3OeULKSs8SXcqnHK1Ogs7rgJjiaH+LYmGjCwSvhEq+yeC+Dx2uufuPSOkVIji6lNvrECaFtn5+0DcacjG3/nvwMi954NbnoWCkCpnI1pdg29p+bPazrL0DUEsDBBQAAAAIAJibNF2abzx8tQAAACkBAAAaAAAAeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHONz80KwjAMB/C7T1Fyd9k8iMi6XUTYVeYDlC77YFtbmvqxt7d4EAcePIXkT34hefmcJ3Enz4M1ErIkBUFG22YwnYRrfd4eQHBQplGTNSRhIYay2OQXmlSIO9wPjkVEDEvoQ3BHRNY9zYoT68jEpLV+ViG2vkOn9Kg6wl2a7tF/G1CsTFE1EnzVZCDqxdE/tm3bQdPJ6ttMJvw4gQ/rR+6JQkSV7yhI+IwY3yVLogpY5Lj6sHgBUEsDBBQAAAAIAJibNF2ToJa7hwAAAKgAAAAYAAAAeGwvd29ya3NoZWV0cy9zaGVldDEueG1sTY3NDsIgEITvPgXZuwU9GGOAXoxPoA+waddCLAthiT9vb9OD8TYzX2bG9u80qydViZkd7DoDinjIY+TJwe162R5BSUMecc5MDj4k0PuNfeX6kEDU1DLA4iC0Vk5ayxAooXS5EC/knmvCttg6aSmVcFxLadZ7Yw46YWTwds3O2NBb/a9/J/4LUEsBAhQDFAAAAAgAmJs0XcUvHX0AAQAALgIAABMAAAAAAAAAAAAAAIABAAAAAFtDb250ZW50X1R5cGVzXS54bWxQSwECFAMUAAAACACYmzRdBlnHgrEAAAAoAQAACwAAAAAAAAAAAAAAgAExAQAAX3JlbHMvLnJlbHNQSwECFAMUAAAACACYmzRdd0D+xLwAAAAcAQAADwAAAAAAAAAAAAAAgAELAgAAeGwvd29ya2Jvb2sueG1sUEsBAhQDFAAAAAgAmJs0XZpvPHy1AAAAKQEAABoAAAAAAAAAAAAAAIAB9AIAAHhsL19yZWxzL3dvcmtib29rLnhtbC5yZWxzUEsBAhQDFAAAAAgAmJs0XZOglruHAAAAqAAAABgAAAAAAAAAAAAAAIAB4QMAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbFBLBQYAAAAABQAFAEUBAACeBAAAAAA=',
  pptx: 'UEsDBBQAAAAIALO9M11W2HDuCgEAANkCAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbLWSuU4DMRCG+zyF5TaKnVAghHY3BUfHUYQHGHlnNxa+5HGi5O2ZHIgFEUgB5Xj+45Ptar7xTqwxk42hljM1lQKDia0NfS1fFveTKymoQGjBxYC13CLJeTOqFtuEJNgcqJbLUtK11mSW6IFUTBh408XsofCYe53AvEKP+mI6vdQmhoKhTMouQzYjIapb7GDlirjb8ObAktGRFDcH7a6ulpCSswYK7/U6tF+KJscSxc69hpY20ZgFUp8q2S1Pd3xYn/iKsm1RPEMuj+BZqFMqOmUktu7l6uewb4Bj11mDbTQrzxY1DPPu06g82DD+nYccHz4AFX7R4TD7a7hB9rlYR6D/QXmHqPT+ZzZvUEsDBBQAAAAIALO9M1062VMktAAAADEBAAALAAAAX3JlbHMvLnJlbHONz80KwjAMB/D7nqLk7rp5EBG7XUTYVeYDlDbrhusHTRX39hZPTjx4TPLPL+TYPu3MHhhp8k5AXVbA0CmvJ2cEXPvzZg+MknRazt6hgAUJ2qY4XnCWKe/QOAViGXEkYEwpHDgnNaKVVPqALk8GH61MuYyGB6lu0iDfVtWOx08DmoKxFcs6LSB2ugbWLwH/4f0wTApPXt0tuvTjylciyzIaTAJCSDxEpNx8p8ssA8+P8tWnzQtQSwMEFAAAAAgAs70zXVYKHMPuAAAAwQEAABQAAABwcHQvcHJlc2VudGF0aW9uLnhtbI2Qz07DMAyH73uKyHeWthpTqZrugiYhwQl4gCh110j5pzhDG09POjoocOEW27/vk+N2d7KGvWEk7Z2Acl0AQ6d8r91BwOvL/qYGRkm6XhrvUMAZCXbdqg1NiEjokkyZZNniqAkCxpRCwzmpEa2ktQ/o8mzw0cqUy3jgS84aXhXFllupHcyS+B+JHwat8N6ro82uT0lEc5HSqANBt2Isb0mmf5KUMD70j5S6nx2m+/xnYLGZHrlRAu9a/of6Ui0lM14t8Oob/wU+vzN1EnBXbjZFkW+szgK29W09FXyOOZ+Q5uB1dgleqRyc7MsDdh9QSwMEFAAAAAgAs70zXVJZ2urAAAAAvwEAAB8AAABwcHQvX3JlbHMvcHJlc2VudGF0aW9uLnhtbC5yZWxzrZDBCsIwDIbvPkXJ3XXbQUTWeRM8eBF9gLDGbdi1pSni3t4iIk4UPHjMn+TLR6r1dTDiQoF7ZxUUWQ6CbON0b1sFx8NmvgTBEa1G4ywpGIlhXc+qPRmMaYe73rNIEMsKuhj9SkpuOhqQM+fJps7JhQFjKkMrPTZnbEmWeb6Q4ZUB9UyICVZstYKw1QWIw+jpJ3wgJhvviMF8uCLZ9Jp2yJFCwmJoKSp4CScTRZb4IL+alX83e3N6pE+PSk7+Xt8AUEsDBBQAAAAIALO9M11hM2flCwEAAN4BAAAhAAAAcHB0L3NsaWRlTWFzdGVycy9zbGlkZU1hc3RlcjEueG1sXZFLbsIwEIb3OYU1e3AIEFURCbu2Gyok6AGMbZIIv2RbEb19xxBTqSv/8817vNvftSKT9GG0poXVsgQiDbdiNH0L3+f3xRuQEJkRTFkjW/iRAfZdsXNNUOLAQpSeYAkTGtfCEKNrKA18kJqFpXXSoO9qvWYRTd9T52WQJrKI7bSiVVnWVLPRQFcQgkX5SYkuFXdnL2VSZvrw7uSOPhn8azp6MgqcFIhhGgcCOjvmMPpMegj6L71/hdC/FnTuOg+g/IE5culXLaiIXeIdlbihuvRVYlViVWKoGOe4DkbMIpMqk1fMOpN1JptMNplsM9lmUmdSAxnUaG545PQAuVr1+QRZ4SWKx2L5Y7pfUEsDBBQAAAAIALO9M10/LUOK0wAAAFwBAAAVAAAAcHB0L3NsaWRlcy9zbGlkZTEueG1sjY9NTsQwDIX3PUXkPePCAqFq2tkg2KGRZjhAlLhtpMSJ4lDB7Uk7FUis2D3/vO/Zx9Nn8GqhLC5yD/eHFhSxidbx1MP79eXuCZQUzVb7yNTDFwmchuaYOvFWVTNLl3qYS0kdopiZgpZDTMR1NsYcdKllnjBlEuKiSw0KHh/a9hGDdgw7JP8HEsfRGXqO5iNU1g2SyW9QmV0SGBql6nHm4u2wHpmumWhVvLzmdEnnvBbmbTln5Wz9GBTrUB8D3Af7Gt5Mm8A/9ulnBX8jcE9ttmYV31BLAQIUAxQAAAAIALO9M11W2HDuCgEAANkCAAATAAAAAAAAAAAAAACAAQAAAABbQ29udGVudF9UeXBlc10ueG1sUEsBAhQDFAAAAAgAs70zXTrZUyS0AAAAMQEAAAsAAAAAAAAAAAAAAIABOwEAAF9yZWxzLy5yZWxzUEsBAhQDFAAAAAgAs70zXVYKHMPuAAAAwQEAABQAAAAAAAAAAAAAAgABGAIAAHBwdC9wcmVzZW50YXRpb24ueG1sUEsBAhQDFAAAAAgAs70zXVJZ2urAAAAAvwEAAB8AAAAAAAAAAAAAAIABOAMAAHBwdC9fcmVscy9wcmVzZW50YXRpb24ueG1sLnJlbHNQSwECFAMUAAAACACzvTNdYTNn5QsBAADeAQAAIQAAAAAAAAAAAAAAgAE1BAAAcHB0L3NsaWRlTWFzdGVycy9zbGlkZU1hc3RlcjEueG1sUEsBAhQDFAAAAAgAs70zXT8tQ4rTAAAAXAEAABUAAAAAAAAAAAAAAgABfwUAAHBwdC9zbGlkZXMvc2xpZGUxLnhtbFBLBQYAAAAABgAGAJsBAACFBgAAAAA=',
}

const DECODED: Record<'docx' | 'xlsx' | 'pptx', Buffer | null> = {
  docx: null,
  xlsx: null,
  pptx: null,
}

for (const ext of ['docx', 'xlsx', 'pptx'] as const) {
  try {
    DECODED[ext] = Buffer.from(BLANK_TEMPLATES[ext], 'base64')
  } catch {
    DECODED[ext] = null
  }
}

/** Returns a decoded blank template, or `null` if decoding failed. */
export function readBlankTemplate(ext: 'docx' | 'xlsx' | 'pptx'): Buffer | null {
  return DECODED[ext]
}

/**
 * Materialise a real, openable file at `path` from the embedded template.
 *
 * Returns `true` when a non-empty file ends up on disk, `false` when the
 * template is missing or the write fails (e.g. read-only storage). Callers
 * should still append to recents in the false case so the user can find
 * the row and trigger a save — without it the click would just vanish.
 */
export function writeBlankOfficeFile(ext: 'docx' | 'xlsx' | 'pptx', path: string): boolean {
  const tpl = readBlankTemplate(ext)
  if (!tpl) return false
  try {
    writeFileSync(path, tpl)
    return true
  } catch {
    return false
  }
}
